### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by frozenpandaman** [aycabta/pawoo-disable-spoiler#1]
No longer works. Image area turns blank.

**Comment by frozenpandaman** [comment]
Similar, working script for all Mastodon instances: https://greasyfork.org/en/scripts/29228-mastodon-nsfw-remover/code

**Comment by frozenpandaman** [comment]
thanks!

**Comment by aycabta** [comment]
https://openuserjs.org/scripts/aycabta/Pawoo_Disable_Spoiler

The 0.1.0 is released. Thank you!
